### ISSUE TITLE
Client crash while trying to open the settings via Mod Menu

### ISSUE THREAD

**Issue by sternschnaube** [Roundaround/mc-fabric-pickup-notifications#23]
java.lang.NoSuchMethodError: 'java.util.List me.roundaround.pickupnotifications.roundalib.client.gui.widget.config.SubScreenControl.children()'
	at me.roundaround.pickupnotifications.compat.roundalib.ConfigControlRegister.guiOffsetEditScreenControlFactory(ConfigControlRegister.java:33)
	at me.roundaround.pickupnotifications.roundalib.client.gui.widget.config.ConfigListWidget$OptionEntry.<init>(ConfigListWidget.java:135)
	at me.roundaround.pickupnotifications.roundalib.client.gui.widget.config.ConfigListWidget.<init>(ConfigListWidget.java:57)
	at me.roundaround.pickupnotifications.roundalib.client.gui.screen.ConfigScreen.method_25426(ConfigScreen.java:44)
	at net.minecraft.class_437.method_25423(class_437.java:427)
	at net.minecraft.class_310.method_1507(class_310.java:1079)
	at com.terraformersmc.modmenu.gui.ModsScreen.lambda$init$1(ModsScreen.java:138)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:57)
	at net.minecraft.class_339.method_25402(class_339.java:187)
	at net.minecraft.class_4069.method_25402(class_4069.java:537)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:209)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1238)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Roundaround** [comment]
Sorry about the trouble! After a LOT of trial and error (and with the help of some folks in the Fabric community), I finally figured out how to fix it. Check out v1.4.1 on Modrinth!

https://modrinth.com/mod/pickup-notifications/version/1.4.1

**Comment by sternschnaube** [comment]
Awesome, thanks alot!
