### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by sternschnaube** [Roundaround/mc-fabric-pickup-notifications#24]
Latest Fabric and mod version.

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayDeque.nonNullElementAt(ArrayDeque.java:270)
	at java.base/java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:700)
	at me.roundaround.pickupnotifications.client.gui.hud.PickupNotificationsHud.render(PickupNotificationsHud.java:65)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$dlo001$fabric-rendering-v1$render(class_329.java:6386)
	at net.minecraft.class_329.method_1753(class_329.java:370)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Roundaround** [comment]
Fixed for 1.20/1.20.1 in version 1.5.2 and for 1.20.2 in 1.6.1! Thanks for reporting!

https://modrinth.com/mod/pickup-notifications/versions
